### ISSUE TITLE
Entité Climate plus fournie par l'intégration

### ISSUE THREAD

**Issue by Bibouche** [maheus/fumis_integration#11]
Bonjour @maheus 

Le froid arrivant, j'ai décidé de rallumer mon poele afin de voir si tout fonctionnait correctement.
J'en ai donc également profité pour vérifier si tout est bon du côté de l'intégration fumis sur Home Assistant.
J'ai toutes les entités qui fonctionnent sauf la plus importante : climate.pellet.....
J'ai redémarré, rechargé l'intégration mais rien ne change, celle ci ne fonctionne plus et n'est plus fournie par l'intégration.
Une idée de ce que cela peut etre ?

Sachant que tout fonctionne sur l'application officielle

Je te joins les logs et une capture: 
![Fumis](https://github.com/maheus/fumis_integration/assets/112384703/c44e6e30-35d6-470c-8284-23d3c991d355)

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Thermostat (documentation, issues)
First occurred: 16:17:39 (1 occurrences)
Last logged: 16:17:39

Error adding entities for domain climate with platform fumis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() argument after ** must be a mapping, not list

```

**Comment by Bibouche** [comment]
J'ai finalement désinstallé et réinstallé l'intégration fumis par HACS en dépôt personnalisé et tout refonctionne. 
J'ai vu sur un autre post qu'avec les nouvelles mise à jour de HA, il a fallu reprogrammer tout ça.
Du coup j'ai à nouveau toutes mes entités qui fonctionnent.
Par contre, j'ai le même problème qu'au départ, sur mon post précédent : le fait de ne pas pouvoir modifier la puissance de mon poele car le service fumis.set_power.stove n'est plus disponible

**Comment by maheus** [comment]
désolé je n'ai pas eu de notif pour votre premier message, je check pour le pb de service

**Comment by maheus** [comment]
ok avec le refacto j'ai fait sauté le service

**Comment by Bibouche** [comment]
Pas de soucis.
Le problème vient de là alors

**Comment by maheus** [comment]
@Bibouche  pouvez vous tester la nouvelle version svp 2.1.0

**Comment by Bibouche** [comment]
J'ai mis la nouvelle version et j'ai bien le nouveau service, par contre le service ne fonctionne toujours pas.

Voici le code erreur 

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 22:56:52 (4 occurrences)
Last logged: 23:18:15

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'Fumis' object has no attribute 'set_power'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/fumis/climate.py", line 244, in set_power_stove
    await self.fumis.set_power(power)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Fumis' object has no attribute 'set_power'
```
le second :
```

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/fumis/climate.py:244
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:56:52 (4 occurrences)
Last logged: 23:18:15

[546706077888] Error handling message: Unknown error (unknown_error) Nagui from 192.xxx.x.xx (Mozilla/5.0 (Linux; Android 13; SM-G990B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36 Home Assistant/2023.10.2-11484 (Android 13; SM-G990B))
[546704724544] Error handling message: Unknown error (unknown_error) Nagui from 192.xxx.x.x (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 727, in handle_execute_script
    script_result = await script_obj.async_run(msg.get("variables"), context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/fumis/climate.py", line 244, in set_power_stove
    await self.fumis.set_power(power)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Fumis' object has no attribute 'set_power'
```

**Comment by maheus** [comment]
:( je fix

**Comment by maheus** [comment]
j'aurais du tester le service, normalement avec la derniere version c good

**Comment by Bibouche** [comment]
Magnifique ! Tout refonctionne comme avant, c'est génial.
Encore une fois Merci à toi. Ton intégration mets grandement utile

**Comment by maheus** [comment]
pas de problème, il faudrait que j'ajoute une ou deux fonctionnalités mais il faut trouver le temps . bonne soirée
