### ISSUE TITLE
Fumis no entities

### ISSUE THREAD

**Issue by Lirik-JuKi** [maheus/fumis_integration#4]
I did the integration without any problems, but no entities or devices appear to me.
for curl curl -H 'username:0016D00+++++' -H 'password:++++' https://api.fumis.si/v1/status/
have answer: {"apiVersion":"1.0","unit":{"id":"0016D00

**Comment by maheus** [comment]
hi @Lirik-JuKi ,

do you have any errors in homeassitant log ?

**Comment by Lirik-JuKi** [comment]
yes.
`Logger: homeassistant.components.sensor
Source: custom_components/fumis/fumis/models.py:103
Integration: Сенсор ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:18:27 (5 occurrences)
Last logged: 12:18:27

fumis: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/fumis/sensor.py", line 140, in async_update
    self.info = await self.fumis.update_info()
  File "/config/custom_components/fumis/fumis/fumis.py", line 123, in update_info
    self.info = Info.from_dict(data)
  File "/config/custom_components/fumis/fumis/models.py", line 103, in from_dict
    ecomode_type=int(ecoMode.get("ecoModeSetType", "Unknown")),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by maheus** [comment]
ok i think i understood

**Comment by maheus** [comment]
there is a problem with ecomode , please replace "Unknown" by -1 
```
 ecomode_type=int(ecoMode.get("ecoModeSetType", -1)),
```

and restart

**Comment by Lirik-JuKi** [comment]
no any result.
`
Logger: homeassistant.components.sensor
Source: custom_components/fumis/fumis/models.py:103
Integration: Сенсор (documentation, issues)
First occurred: 13:26:17 (15 occurrences)
Last logged: 13:29:45

fumis: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/fumis/sensor.py", line 140, in async_update
    self.info = await self.fumis.update_info()
  File "/config/custom_components/fumis/fumis/fumis.py", line 123, in update_info
    self.info = Info.from_dict(data)
  File "/config/custom_components/fumis/fumis/models.py", line 103, in from_dict
    ecomode_type=int(ecoMode.get("ecoModeSetType", -1)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by maheus** [comment]
:( same error , i suppose ecoModeSetType not send anything

**Comment by maheus** [comment]
in curl response , do you have :
```
    "ecoMode": {
      "ecoModeSetType": 1,
      "ecoModeEnable": 1
    },
```
?

**Comment by Lirik-JuKi** [comment]
i have

"ecoMode":{"ecoModeSetType":null,"ecoModeEnable":null},

**Comment by maheus** [comment]
ok thanks , i fix it this night

**Comment by maheus** [comment]
@Lirik-JuKi do you can test with new version please

**Comment by rmpirescosta** [comment]
I can also express the changes. mine doesn't change the temperature but as is the water the boiler doesn't bother me either. yes to turn it on and off.

**Comment by Lirik-JuKi** [comment]
> @Lirik-JuKi do you can test with new version please
 yes, i can, some minnits, pls

**Comment by Lirik-JuKi** [comment]
The entities have appeared.

![Screenshot 2022-03-02 162340](https://user-images.githubusercontent.com/97107705/156380204-c7e8069b-f684-4bcc-9b4e-9d0b261c9df6.jpg)

There is also a new error in the log

<
Logger: homeassistant.components.climate
Source: custom_components/fumis/climate.py:187
Integration: Климат (documentation, issues)
First occurred: 16:21:02 (4 occurrences)
Last logged: 16:22:43

Error adding entities for domain climate with platform fumis
Error while setting up fumis platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/fumis/climate.py", line 187, in preset_mode
    return FUMIS_PRESET_TO_HA[self._ecomode_state]
KeyError: 'unknown'
>

**Comment by maheus** [comment]
> I can also express the changes. mine doesn't change the temperature but as is the water the boiler doesn't bother me either. yes to turn it on and off.

yes i suppose the temperature change is different because you using a hybride mode (water), you can test with curl . (first curl and after change the temperature on the stove , renew curl and view differences )

**Comment by maheus** [comment]
thanks @Lirik-JuKi , i'm going to fix

**Comment by maheus** [comment]
fix pushed, i force ecomode to 0 if the api return None . temporarly fix for the moment @Lirik-JuKi

**Comment by Lirik-JuKi** [comment]
> 

now it works. thanks.
