### ISSUE TITLE
Entities not available

### ISSUE THREAD

**Issue by Bibouche** [maheus/fumis_integration#8]
Hello,
Since the last HA update, some entities are not available. 
Should something be done?
![1](https://user-images.githubusercontent.com/112384703/236785375-a1a564da-2337-4de6-8c56-b431ece5d802.png)

**Comment by maheus** [comment]
:( i have not yet upgrade, i will fix as fast as possible

**Comment by Bibouche** [comment]
All right, no worriesn thanks

**Comment by maheus** [comment]
you are french ? if yes, you can talk to french if you prefer.
do you have logs after upgrade and restart HA ? do you have look your logs after upgrade and restart HA ? do you have some errors ?

**Comment by Bibouche** [comment]
Oui tout à fait, je suis bien Français, faisons comme ça alors.
Quelques entitées fonctionnent quand je recharge l'intégration mais pas la totalité. Dans tous les cas quand je redémarre HA , les entitées ne sont plus disponibles.

Voici l'erreur du journal :

```
Logger: homeassistant.components.climate
Source: custom_components/fumis/fumis/fumis.py:79
Integration: Thermostat (documentation, issues)
First occurred: 13:34:54 (1 occurrences)
Last logged: 13:34:54

fumis: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/fumis/fumis/fumis.py", line 65, in _request
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fumis/fumis/fumis.py", line 64, in _request
    with async_timeout.timeout(self.request_timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/config/custom_components/fumis/climate.py", line 151, in async_update
    self.info = await self.fumis.update_info()
  File "/config/custom_components/fumis/fumis/fumis.py", line 117, in update_info
    raise exception
  File "/config/custom_components/fumis/fumis/fumis.py", line 114, in update_info
    data = await self._request("status")
  File "/config/custom_components/fumis/fumis/fumis.py", line 79, in _request
    raise FumisConnectionError(
custom_components.fumis.fumis.exceptions.FumisConnectionError: Timeout occurred while connecting to the Fumis WiRCU API

```

**Comment by maheus** [comment]
meric pour les logs , j'ai redemarré HA sans upgrade dans un premier temps et j'ai des erreurs identiques .
De ce que je vois l'api fumis n'est pas en forme, tu peux faire un test avec ``` curl  -v https://api.fumis.si ```
Pour moi ça par en timeout 9 fois sur 10, on va devoir attendre que ça revienne.
dès que le curl passera bien cela devrait rentrer dans l'ordre (un restart sera peut etre necessaire).
Ca fait longtemps que je n'avais pas eu de problème avec l'api.

**Comment by Bibouche** [comment]
Je pense que tu as raison cela doit venir de l'application.
J'ai voulu éteindre mon poele ce matin avec l'application Pelletcontrol et cela ne fonctionnait pas non plus. Pourtant j'ai bien tous les voyants verts.
Cela fait aussi quelques mois que je n'avais pas eu de problèmes mais à une période c'était régulier

**Comment by maheus** [comment]
hello @Bibouche j'ai rechargé l'intégration depuis le menu HA et tout est repartie si tu peux valider stp que je puisse clore le ticket , merci

**Comment by Bibouche** [comment]
Hello @maheus ,
Tout est bon de mon côté également. 
La prochaine fois j'essayerai de voir si tout est ok du côté de l'api fumis
Merci à toi

**Comment by maheus** [comment]
parfait bonne semaine
